# This config file is the an edited version of the default hifigan cfg file for use with M. cruise.
# I added the model.train_ds dataloader options...

name: "HifiGan"

init_from_pretrained_model : "tts_hifigan"

train_dataset: "./manifests/manifest_hifigan_train.json"
validation_datasets: "./manifests/manifest_hifigan_val.json"

sup_data_path: "./hifigan_sup_data"
sup_data_types: [ "align_prior_matrix", "pitch"]

# Default values from librosa.pyin
pitch_fmin: 65.40639132514966
pitch_fmax: 2093.004522404789

pitch_mean: 100.3  # e.g. 212.35873413085938 for LJSpeech
pitch_std:  64  # e.g.  68.52806091308594 for LJSpeech

# Default values for dataset with sample_rate=22050
sample_rate: 22050
n_mel_channels: 80
n_window_size: 1024
n_window_stride: 256
n_fft: 1024
lowfreq: 0
highfreq: 8000
window: hann

train_n_segments: 8192
train_max_duration: null
train_min_duration: 0.75

val_n_segments: 66048
val_max_duration: null
val_min_duration: 3

defaults:
      - model/generator: v1
#    #  - model/train_ds: train_ds_finetune
#    #  - model/validation_ds: val_ds_finetune

phoneme_dict_path: "tts_dataset_files/cmudict-0.7b_nv22.10"
heteronyms_path: "tts_dataset_files/heteronyms-052722"
whitelist_path: "tts_dataset_files/tts.tsv"

model:

  pitch_fmin: ${pitch_fmin}
  pitch_fmax: ${pitch_fmax}
  pitch_mean: ${pitch_mean}
  pitch_std: ${pitch_std}

  sample_rate: ${sample_rate}
  n_mel_channels: ${n_mel_channels}
  n_window_size: ${n_window_size}
  n_window_stride: ${n_window_stride}
  n_fft: ${n_fft}
  lowfreq: ${lowfreq}
  highfreq: ${highfreq}
  window: ${window}

  # text_normalizer:
  #   _target_: nemo_text_processing.text_normalization.normalize.Normalizer
  #   lang: en
  #   input_case: cased
  #   whitelist: ${whitelist_path}

  # text_normalizer_call_kwargs:
  #   verbose: false
  #   punct_pre_process: true
  #   punct_post_process: true

  # text_tokenizer:
  #   _target_: nemo.collections.common.tokenizers.text_to_speech.tts_tokenizers.EnglishPhonemesTokenizer
  #   punct: true
  #   stresses: true
  #   chars: true
  #   apostrophe: true
  #   pad_with_space: true
  #   add_blank_at : true
  #   g2p:
  #     _target_: nemo_text_processing.g2p.modules.EnglishG2p
  #     phoneme_dict: ${phoneme_dict_path}
  #     heteronyms: ${heteronyms_path}
  #     phoneme_probability: 0.5

  train_ds:
    dataset:
      _target_: nemo.collections.tts.torch.data.TTSDataset
      manifest_filepath: ${train_dataset}
      sample_rate: ${model.sample_rate}
      sup_data_path: ${sup_data_path}
      sup_data_types: ${sup_data_types}
      n_fft: ${model.n_fft}
      win_length: ${model.n_window_size}
      hop_length: ${model.n_window_stride}
      window: ${model.window}
      n_mels: ${model.n_mel_channels}
      lowfreq: ${model.lowfreq}
      highfreq: ${model.highfreq}
      max_duration: null
      min_duration: 0.1
      ignore_file: null
      trim: false
      pitch_fmin: ${model.pitch_fmin}
      pitch_fmax: ${model.pitch_fmax}
      pitch_norm: true
      pitch_mean: ${model.pitch_mean}
      pitch_std: ${model.pitch_std}
      use_beta_binomial_interpolator: true

    dataloader_params:
      drop_last: false
      shuffle: true
      batch_size: 24
      num_workers: 8
      pin_memory: true
  
  validation_ds:
    dataset:
      _target_: nemo.collections.tts.torch.data.TTSDataset
      manifest_filepath: ${validation_datasets}
      sample_rate: ${model.sample_rate}
      sup_data_path: ${sup_data_path}
      sup_data_types: ${sup_data_types}
      n_fft: ${model.n_fft}
      win_length: ${model.n_window_size}
      hop_length: ${model.n_window_stride}
      window: ${model.window}
      n_mels: ${model.n_mel_channels}
      lowfreq: ${model.lowfreq}
      highfreq: ${model.highfreq}
      max_duration: null
      min_duration: null
      ignore_file: null
      trim: false
      pitch_fmin: ${model.pitch_fmin}
      pitch_fmax: ${model.pitch_fmax}
      pitch_norm: true
      pitch_mean: ${model.pitch_mean}
      pitch_std: ${model.pitch_std}
      use_beta_binomial_interpolator: true

    dataloader_params:
      drop_last: false
      shuffle: false
      batch_size: 24
      num_workers: 8
      pin_memory: true

  preprocessor:
    _target_: nemo.collections.asr.parts.preprocessing.features.FilterbankFeatures
    nfilt: ${n_mel_channels}
    lowfreq: ${lowfreq}
    highfreq: ${highfreq}
    n_fft: ${n_fft}
    n_window_size: ${n_window_size}
    n_window_stride: ${n_window_stride}
    pad_to: 0
    pad_value: -11.52
    sample_rate: ${sample_rate}
    window: ${window}
    normalize: null
    preemph: null
    dither: 0.0
    frame_splicing: 1
    log: true
    log_zero_guard_type: clamp
    log_zero_guard_value: 1e-05
    mag_power: 1.0
    use_grads: false
    exact_pad: true

  optim:
    _target_: torch.optim.AdamW
    lr: 0.00001
    betas: [0.8, 0.99]

  max_steps: 10000
  l1_loss_factor: 45
  denoise_strength: 0.0025

trainer:
  num_nodes: 1
  devices: 1
  accelerator: gpu
  strategy: ddp
  precision: 32
  max_steps: ${model.max_steps}
  accumulate_grad_batches: 1
  enable_checkpointing: False  # Provided by exp_manager
  logger: false # Provided by exp_manager
  log_every_n_steps: 100
  check_val_every_n_epoch: 10
  benchmark: false

exp_manager:
  exp_dir: "./exp/hifigan_cruisetuningv1"
  name: ${name}
  create_tensorboard_logger: true
  create_checkpoint_callback: true
  checkpoint_callback_params:
    monitor: val_loss
    mode: min
  create_wandb_logger: false
  wandb_logger_kwargs:
    name: null
    project: null
    entity: null
  resume_if_exists: false
  resume_ignore_no_checkpoint: false
