cfg:
  generator:
    _target_: nemo.collections.tts.modules.hifigan_modules.Generator
    resblock: 1
    upsample_rates:
    - 8
    - 8
    - 2
    - 2
    upsample_kernel_sizes:
    - 16
    - 16
    - 4
    - 4
    upsample_initial_channel: 512
    resblock_kernel_sizes:
    - 3
    - 7
    - 11
    resblock_dilation_sizes:
    - - 1
      - 3
      - 5
    - - 1
      - 3
      - 5
    - - 1
      - 3
      - 5
  train_ds:
    dataset:
      _target_: nemo.collections.tts.torch.data.VocoderDataset
      manifest_filepath: ./manifests/manifest_hifigan_train.json
      sample_rate: 22050
      n_segments: 8192
      max_duration: null
      min_duration: 0.75
      load_precomputed_mel: true
      hop_length: 256
    dataloader_params:
      drop_last: false
      shuffle: true
      batch_size: 16
      num_workers: 4
      pin_memory: true
  validation_ds:
    dataset:
      _target_: nemo.collections.tts.torch.data.VocoderDataset
      manifest_filepath: ./manifests/manifest_hifigan_val.json
      sample_rate: 22050
      n_segments: 66048
      max_duration: null
      min_duration: 3
      load_precomputed_mel: true
      hop_length: 256
    dataloader_params:
      drop_last: false
      shuffle: false
      batch_size: 16
      num_workers: 4
      pin_memory: true
  preprocessor:
    _target_: nemo.collections.asr.parts.preprocessing.features.FilterbankFeatures
    nfilt: 80
    lowfreq: 0
    highfreq: 8000
    n_fft: 1024
    n_window_size: 1024
    n_window_stride: 256
    pad_to: 0
    pad_value: -11.52
    sample_rate: 22050
    window: hann
    normalize: null
    preemph: null
    dither: 0.0
    frame_splicing: 1
    log: true
    log_zero_guard_type: clamp
    log_zero_guard_value: 1.0e-05
    mag_power: 1.0
    use_grads: false
    exact_pad: true
  optim:
    _target_: torch.optim.AdamW
    lr: 1.0e-05
    betas:
    - 0.8
    - 0.99
  max_steps: 10000
  l1_loss_factor: 45
  denoise_strength: 0.0025
  target: nemo.collections.tts.models.hifigan.HifiGanModel
  nemo_version: 1.14.0
